######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 30 12:46:14 2015
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT      += core gui webkit webkitwidgets network 
